### ISSUE TITLE
Default Themes for Frontend and Backend not in composer installation

### ISSUE THREAD

**Issue by azngeek** [shopware/composer-project#70]
It seems like that with composer the default templates are not available. Also they are in the gitignore. The question is: What is the correct way to install them? I could not find any hint. 

```
# Themes
/themes/Backend/ExtJs
/themes/Frontend/Bare
/themes/Frontend/Responsive
/themes/grunt-tasks
/themes/Gruntfile.js
/themes/package.json
```

And they are present in the standard repository: https://github.com/shopware/shopware

**Comment by larsbo** [comment]
they will be sym-linked after running /app/bin/install.sh

see https://github.com/shopware5/composer-project/blob/6c3a8a7c21e01ca6ebed6d1159378b8036525e2a/app/bin/post-install.sh#L5

**Comment by mitelg** [comment]
which is defined here: https://github.com/shopware5/composer-project/blob/5.7/app/bin/functions.sh#L176
