### ISSUE TITLE
Shopware PayPal Plugin

### ISSUE THREAD

**Issue by azngeek** [shopware/composer-project#71]
It seems like that the Plugin should be pre-installed, but it is not: https://store.shopware.com/swag828732772311f/paypal-fuer-shopware-5.html 

It also seems that the plugin does exists in his own repository: https://github.com/shopwareLabs/SwagPaymentPayPalUnified
However it can not be bought and so is not available in my Shopware license list.

What is the best practice to install this and other "default" plugins?

**Comment by mitelg** [comment]
hey @azngeek 

if you are using this composer template, you can just do `composer require shopware-labs/swag-payment-paypal-unified`

This will add the plugin via composer and is installable and usable as normal afterwards
