### ISSUE TITLE
Add .htaccess optimization

### ISSUE THREAD

**Issue by bonokburn** [shopware/composer-project#72]
Hi there!

It would be good to include the change made to the .htaccess in the Composer Project as well:

`RedirectMatch 404 /themes/(.*)(.*\.lock|package\.json|\.gitignore|Gruntfile\.js|all\.less|node_modules\/.*)$`
=>
`RedirectMatch 404 /themes/(.*)(.(lock|package)\.json|\.gitignore|Gruntfile\.js|all\.less|node_modules\/.*)$`

**Note:** 
Maybe the regex pattern should be reconsidered in general, because this file should be protected, but it is not:
https://domain.de/themes/package.json

Kind Regards
Frank

**Comment by mitelg** [comment]
@shopware5/shopware-core could you have a look here?
